name: Deploy to GoDaddy cPanel

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Install zip and lftp
      run: sudo apt-get update && sudo apt-get install -y zip lftp

    - name: Zip build artifacts
      run: |
        cd out
        zip -r ../build.zip ./*
        cd ..

    - name: Deploy via SFTP
      run: |
        lftp -e "
          set ftp:ssl-allow no;
          open -u $FTP_USERNAME,$FTP_PASSWORD -p 2222 $FTP_HOST;
          mkdir -p public_html;
          cd public_html;
          put build.zip;
          bye"
      env:
        FTP_HOST: s3cura.com
        FTP_USERNAME: iqfu27x9dob7
        FTP_PASSWORD: Gaurav123#

    - name: Unzip on server
      run: |
        lftp -e "
          set ftp:ssl-allow no;
          open -u $FTP_USERNAME,$FTP_PASSWORD -p 2222 $FTP_HOST;
          cd public_html;
          !unzip -o build.zip;
          !rm build.zip;
          bye"
      env:
        FTP_HOST: s3cura.com
        FTP_USERNAME: iqfu27x9dob7
        FTP_PASSWORD: Gaurav123#