name: Deploy to GoDaddy via FTP

on:
  push:
    branches:
      - home_page

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Static Site
        run: npm run build

      - name: Zip the Build Folder
        run: |
          cd out
          zip -r ../site.zip .
          cd ..

      - name: Upload ZIP and PHP Script
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: s3cura.ai
          username: iqfu27x9dob7
          password: Gaurav123#
          local-dir: ./
          server-dir: /public_html/
          exclude: |
            **/.git*
            **/node_modules/*
            **/scripts/*
            out/**

      - name: Upload unzip.php
        run: cp scripts/unzip.php ./unzip.php
